name: Compilar Aseprite para Windows 32 bits
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    # CORRECCIÓN DEFINITIVA: Clonación manual para saltarnos el limpiador de GitHub
    - name: Descargar codigo fuente manualmente
      run: git clone https://github.com/aseprite/aseprite.git .

    - name: Configurar herramientas de desarrollo x86
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Instalar Ninja y CMake
      run: choco install ninja cmake

    - name: Descargar precompilado de Skia 32 bits
      run: |
        curl -L -o skia.zip https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x86.zip
        expand-archive skia.zip -DestinationPath c:\skia

    - name: Compilar Aseprite x86
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -A Win32 -DLAF_BACKEND=skia -DSKIA_DIR=c:\skia -DSKIA_LIBRARY_DIR=c:\skia\out\Release-x86 -G Ninja ..
        ninja aseprite

    - name: Subir archivo final 32 bits
      uses: actions/upload-artifact@v4
      with:
        name: Aseprite-Windows-32bit-Listo
        path: build/bin/
