name: Compilar Aseprite para Windows 32 bits
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Descargar codigo fuente
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    # Corrección: Se fuerza la versión compatible de MSVC
    - name: Configurar herramientas de desarrollo x86
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x86

    - name: Instalar Ninja y CMake
      run: choco install ninja cmake

    - name: Descargar precompilado de Skia 32 bits
      run: |
        curl -L -o skia.zip https://github.com
        expand-archive skia.zip -DestinationPath c:\skia

    - name: Compilar Aseprite x86
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=c:\skia -DSKIA_LIBRARY_DIR=c:\skia\out\Release-x86 -G Ninja ..
        ninja aseprite

    # Corrección: Versión actualizada del cargador de archivos
    - name: Subir archivo final 32 bits
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Aseprite-Windows-32bit-Listo
        path: build/bin/
